import argparse
import json
import os
import random

import numpy as np
import pandas as pd
from angle_emb import AnglE
from simcse import SimCSE
from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans


np.random.seed(0)
random.seed(0)


LABEL_MAP = {
    0: "not_hate",
    1: "implicit_hate",
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Cluster high-confidence pseudo-labeled COLD samples and keep only pure clusters."
    )
    parser.add_argument(
        "--pseudo_predictions",
        default="save/simcse/sbert-multi_ihc_pure_c10/0/cold_train_predictions.csv",
        type=str,
        help="Path to cold_train_predictions.csv generated by eval.py.",
    )
    parser.add_argument(
        "--output_dir",
        default="pseudo_clusters/sbert-multi_cold_conf099_k50",
        type=str,
        help="Directory to save clustered pseudo-sample outputs.",
    )
    parser.add_argument(
        "--confidence_threshold",
        default=0.99,
        type=float,
        help="Keep pseudo samples with confidence >= this threshold before clustering.",
    )
    parser.add_argument(
        "--cluster_num",
        default=50,
        type=int,
        help="Number of KMeans clusters.",
    )
    parser.add_argument(
        "--min_cluster_size",
        default=5,
        type=int,
        help="Minimum cluster size to keep.",
    )
    parser.add_argument(
        "--purity_threshold",
        default=0.80,
        type=float,
        help="Minimum majority-label ratio required to keep a cluster.",
    )
    parser.add_argument(
        "--balanced_margin",
        default=0.10,
        type=float,
        help="Drop clusters whose majority ratio is within 0.5 +/- this margin.",
    )
    parser.add_argument(
        "--load_sent_emb_model",
        default="sbert-multi",
        type=str,
        help="Sentence embedding model name.",
    )
    parser.add_argument(
        "--seed",
        default=0,
        type=int,
        help="Random seed.",
    )
    return parser.parse_args()


def load_sentence_encoder(model_name):
    print(f"LOAD_SENT_EMB_MODEL: {model_name}", flush=True)
    if model_name == "simcse":
        return SimCSE("princeton-nlp/sup-simcse-roberta-large")
    if model_name == "angle":
        return AnglE.from_pretrained(
            "SeanLee97/angle-bert-base-uncased-nli-en-v1",
            pooling_strategy="cls_avg",
        ).cuda()
    if model_name == "sbert":
        return SentenceTransformer("all-MiniLM-L6-v2")
    if model_name == "sbert-multi":
        return SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
    raise NotImplementedError(f"Unsupported sentence embedding model: {model_name}")


def filter_high_confidence_samples(predictions, threshold):
    filtered = predictions.loc[predictions["confidence"] >= threshold].copy()
    filtered = filtered.sort_values("confidence", ascending=False).reset_index(drop=True)
    return filtered


def summarize_cluster(cluster_df, cluster_id, min_cluster_size, purity_threshold, balanced_margin):
    label_counts = cluster_df["pred_label"].value_counts().to_dict()
    count_0 = int(label_counts.get(0, 0))
    count_1 = int(label_counts.get(1, 0))
    cluster_size = len(cluster_df)
    majority_label = 1 if count_1 >= count_0 else 0
    majority_count = max(count_0, count_1)
    majority_ratio = majority_count / cluster_size
    is_balanced = abs(majority_ratio - 0.5) <= balanced_margin
    keep_cluster = (cluster_size >= min_cluster_size) and (majority_ratio >= purity_threshold) and (not is_balanced)

    return {
        "cluster": cluster_id,
        "cluster_size": cluster_size,
        "count_0": count_0,
        "count_1": count_1,
        "majority_label": majority_label,
        "majority_class_name": LABEL_MAP[majority_label],
        "majority_ratio": majority_ratio,
        "is_balanced_cluster": is_balanced,
        "keep_cluster": keep_cluster,
    }


def main():
    args = parse_args()
    np.random.seed(args.seed)
    random.seed(args.seed)

    predictions = pd.read_csv(args.pseudo_predictions)
    filtered = filter_high_confidence_samples(predictions, args.confidence_threshold)
    if len(filtered) < args.cluster_num:
        raise ValueError(
            f"Filtered sample count ({len(filtered)}) is smaller than cluster_num ({args.cluster_num}). "
            "Lower cluster_num or lower confidence_threshold."
        )

    encoder = load_sentence_encoder(args.load_sent_emb_model)
    embeddings = np.array(encoder.encode(filtered["post"].fillna("").astype(str).tolist()))

    kmeans = KMeans(n_clusters=args.cluster_num, random_state=args.seed, n_init="auto").fit(embeddings)
    filtered["cluster"] = kmeans.labels_.tolist()

    cluster_summaries = []
    for cluster_id, cluster_df in filtered.groupby("cluster"):
        cluster_summaries.append(
            summarize_cluster(
                cluster_df,
                cluster_id=cluster_id,
                min_cluster_size=args.min_cluster_size,
                purity_threshold=args.purity_threshold,
                balanced_margin=args.balanced_margin,
            )
        )

    summary_df = pd.DataFrame(cluster_summaries).sort_values(
        ["keep_cluster", "majority_ratio", "cluster_size"],
        ascending=[False, False, False],
    ).reset_index(drop=True)

    filtered = filtered.merge(
        summary_df[
            [
                "cluster",
                "cluster_size",
                "majority_label",
                "majority_class_name",
                "majority_ratio",
                "is_balanced_cluster",
                "keep_cluster",
            ]
        ],
        on="cluster",
        how="left",
    )

    selected = filtered.loc[filtered["keep_cluster"]].copy().reset_index(drop=True)

    os.makedirs(args.output_dir, exist_ok=True)
    filtered_out = os.path.join(args.output_dir, "clustered_high_confidence_samples.csv")
    summary_out = os.path.join(args.output_dir, "cluster_summary.csv")
    selected_out = os.path.join(args.output_dir, "selected_cluster_samples.csv")
    meta_out = os.path.join(args.output_dir, "selection_metadata.json")

    filtered.to_csv(filtered_out, index=False)
    summary_df.to_csv(summary_out, index=False)
    selected.to_csv(selected_out, index=False)

    metadata = {
        "pseudo_predictions": args.pseudo_predictions,
        "load_sent_emb_model": args.load_sent_emb_model,
        "confidence_threshold": args.confidence_threshold,
        "cluster_num": args.cluster_num,
        "min_cluster_size": args.min_cluster_size,
        "purity_threshold": args.purity_threshold,
        "balanced_margin": args.balanced_margin,
        "seed": args.seed,
        "high_confidence_samples": len(filtered),
        "kept_clusters": int(summary_df["keep_cluster"].sum()),
        "kept_samples": len(selected),
    }
    with open(meta_out, "w") as f:
        json.dump(metadata, f, indent=4)

    print(f"Saved {filtered_out}")
    print(f"Saved {summary_out}")
    print(f"Saved {selected_out}")
    print(f"High-confidence samples: {len(filtered)}")
    print(f"Kept clusters: {int(summary_df['keep_cluster'].sum())}")
    print(f"Kept samples: {len(selected)}")


if __name__ == "__main__":
    main()
