import argparse
import json
import os
import random

import numpy as np
import pandas as pd
from angle_emb import AnglE
from simcse import SimCSE
from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances_argmin_min
from sklearn.metrics.pairwise import cosine_similarity

from util import ensure_output_dir_is_new

np.random.seed(0)
random.seed(0)


LABEL_MAP = {
    0: "not_hate",
    1: "implicit_hate",
}

CLASS_TO_LABEL = {
    "not_hate": 0,
    "implicit_hate": 1,
}


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Select high-confidence pseudo-labeled COLD samples, perform global clustering, "
            "drop balanced clusters, align remaining pseudo clusters to base IHC clusters, "
            "and remove pseudo clusters whose class distribution differs too much from the aligned IHC cluster."
        )
    )
    parser.add_argument(
        "--pseudo_predictions",
        default="save/sbert-multi/sbert-multi_ihc_pure_c10/0/cold_train_predictions.csv",
        type=str,
        help="Path to cold_train_predictions.csv generated by eval.py.",
    )
    parser.add_argument(
        "--base_clustered_train",
        default="clustered_dataset/sbert-multi/ihc_pure_c10/train.tsv",
        type=str,
        help="Path to the original clustered IHC train.tsv used as alignment target.",
    )
    parser.add_argument(
        "--output_dir",
        default="pseudo_clusters/sbert-multi_cold_conf099_global_k50_aligned",
        type=str,
        help="Directory to save clustered/aligned pseudo-sample outputs.",
    )
    parser.add_argument(
        "--confidence_threshold",
        default=0.99,
        type=float,
        help="Keep pseudo samples with confidence >= this threshold before clustering.",
    )
    parser.add_argument(
        "--cluster_num",
        default=50,
        type=int,
        help="Number of global KMeans clusters on high-confidence pseudo samples.",
    )
    parser.add_argument(
        "--min_cluster_size",
        default=5,
        type=int,
        help="Minimum cluster size to keep.",
    )
    parser.add_argument(
        "--purity_threshold",
        default=0.80,
        type=float,
        help="Minimum majority-label ratio required to keep a cluster before IHC alignment.",
    )
    parser.add_argument(
        "--balanced_margin",
        default=0.10,
        type=float,
        help="Drop clusters whose majority ratio is within 0.5 +/- this margin.",
    )
    parser.add_argument(
        "--class_ratio_gap_threshold",
        default=0.20,
        type=float,
        help="Maximum allowed positive-class-ratio gap between a pseudo cluster and its aligned IHC cluster.",
    )
    parser.add_argument(
        "--load_sent_emb_model",
        default="sbert-multi",
        type=str,
        help="Sentence embedding model name.",
    )
    parser.add_argument(
        "--seed",
        default=0,
        type=int,
        help="Random seed.",
    )
    return parser.parse_args()


def load_sentence_encoder(model_name):
    local_files_only = os.environ.get("HF_LOCAL_FILES_ONLY", "0") == "1"
    print(f"LOAD_SENT_EMB_MODEL: {model_name}", flush=True)
    if model_name == "simcse":
        return SimCSE("princeton-nlp/sup-simcse-roberta-large")
    if model_name == "angle":
        return AnglE.from_pretrained(
            "SeanLee97/angle-bert-base-uncased-nli-en-v1",
            pooling_strategy="cls_avg",
        ).cuda()
    if model_name == "sbert":
        return SentenceTransformer("all-MiniLM-L6-v2", local_files_only=local_files_only)
    if model_name == "sbert-multi":
        return SentenceTransformer(
            "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
            local_files_only=local_files_only,
        )
    raise NotImplementedError(f"Unsupported sentence embedding model: {model_name}")


def encode_posts(encoder, texts):
    return np.array(encoder.encode(texts.fillna("").astype(str).tolist()))


def filter_high_confidence_samples(predictions, threshold):
    filtered = predictions.loc[predictions["confidence"] >= threshold].copy()
    filtered = filtered.sort_values("confidence", ascending=False).reset_index(drop=True)
    return filtered


def summarize_pseudo_cluster(cluster_df, cluster_id, min_cluster_size, purity_threshold, balanced_margin):
    label_counts = cluster_df["pred_label"].value_counts().to_dict()
    count_0 = int(label_counts.get(0, 0))
    count_1 = int(label_counts.get(1, 0))
    cluster_size = len(cluster_df)
    positive_ratio = count_1 / cluster_size
    majority_label = 1 if count_1 >= count_0 else 0
    majority_count = max(count_0, count_1)
    majority_ratio = majority_count / cluster_size
    is_balanced = abs(majority_ratio - 0.5) <= balanced_margin
    keep_cluster = (cluster_size >= min_cluster_size) and (majority_ratio >= purity_threshold) and (not is_balanced)

    return {
        "cluster": int(cluster_id),
        "cluster_size": cluster_size,
        "count_0": count_0,
        "count_1": count_1,
        "positive_ratio": positive_ratio,
        "majority_label": majority_label,
        "majority_class_name": LABEL_MAP[majority_label],
        "majority_ratio": majority_ratio,
        "is_balanced_cluster": is_balanced,
        "keep_cluster": keep_cluster,
    }


def build_base_cluster_reference(base_df, base_embeddings):
    summary_rows = []
    prototype_rows = []

    for cluster_id, cluster_df in base_df.groupby("cluster"):
        cluster_indices = cluster_df.index.to_list()
        cluster_embeddings = base_embeddings[cluster_indices]
        center = np.mean(cluster_embeddings, axis=0)
        closest, _ = pairwise_distances_argmin_min(center.reshape(1, -1), cluster_embeddings)
        closest_global_idx = cluster_indices[int(closest[0])]

        class_counts = cluster_df["class"].value_counts().to_dict()
        not_hate_count = int(class_counts.get("not_hate", 0))
        implicit_count = int(class_counts.get("implicit_hate", 0))
        cluster_size = len(cluster_df)
        positive_ratio = implicit_count / cluster_size
        majority_label = 1 if positive_ratio >= 0.5 else 0

        summary_rows.append(
            {
                "aligned_target_cluster": int(cluster_id),
                "aligned_base_cluster_size": cluster_size,
                "aligned_base_count_0": not_hate_count,
                "aligned_base_count_1": implicit_count,
                "aligned_base_positive_ratio": positive_ratio,
                "aligned_base_majority_label": majority_label,
                "aligned_base_class_name": LABEL_MAP[majority_label],
            }
        )
        prototype_rows.append(
            {
                "aligned_target_cluster": int(cluster_id),
                "aligned_centroid_embedding": center,
                "aligned_centroid_sample": (
                    cluster_df["centroid_sample"].iloc[0]
                    if "centroid_sample" in cluster_df.columns
                    else base_df.loc[closest_global_idx, "post"]
                ),
            }
        )

    base_summary_df = pd.DataFrame(summary_rows).sort_values("aligned_target_cluster").reset_index(drop=True)
    base_prototype_df = pd.DataFrame(prototype_rows).sort_values("aligned_target_cluster").reset_index(drop=True)
    return base_summary_df, base_prototype_df


def align_pseudo_clusters(summary_df, kmeans_centers, base_summary_df, base_prototype_df, class_ratio_gap_threshold):
    base_centers = np.stack(base_prototype_df["aligned_centroid_embedding"].to_numpy())
    similarity_matrix = cosine_similarity(kmeans_centers, base_centers)

    aligned_rows = []
    for _, row in summary_df.iterrows():
        cluster_id = int(row["cluster"])
        best_idx = int(np.argmax(similarity_matrix[cluster_id]))

        base_summary = base_summary_df.iloc[best_idx]
        base_prototype = base_prototype_df.iloc[best_idx]
        class_ratio_gap = abs(float(row["positive_ratio"]) - float(base_summary["aligned_base_positive_ratio"]))
        alignment_label_match = int(row["majority_label"]) == int(base_summary["aligned_base_majority_label"])
        keep_after_alignment = bool(row["keep_cluster"]) and (class_ratio_gap <= class_ratio_gap_threshold)

        aligned_row = row.to_dict()
        aligned_row.update(
            {
                "aligned_target_cluster": int(base_summary["aligned_target_cluster"]),
                "aligned_centroid_sample": base_prototype["aligned_centroid_sample"],
                "aligned_similarity": float(similarity_matrix[cluster_id][best_idx]),
                "aligned_base_cluster_size": int(base_summary["aligned_base_cluster_size"]),
                "aligned_base_positive_ratio": float(base_summary["aligned_base_positive_ratio"]),
                "aligned_base_majority_label": int(base_summary["aligned_base_majority_label"]),
                "aligned_base_class_name": base_summary["aligned_base_class_name"],
                "class_ratio_gap": class_ratio_gap,
                "alignment_label_match": alignment_label_match,
                "keep_after_alignment": keep_after_alignment,
            }
        )
        aligned_rows.append(aligned_row)

    return pd.DataFrame(aligned_rows).sort_values(
        ["keep_after_alignment", "aligned_similarity", "majority_ratio", "cluster_size"],
        ascending=[False, False, False, False],
    ).reset_index(drop=True)


def main():
    args = parse_args()
    np.random.seed(args.seed)
    random.seed(args.seed)

    predictions = pd.read_csv(args.pseudo_predictions)
    filtered = filter_high_confidence_samples(predictions, args.confidence_threshold)
    if len(filtered) < args.cluster_num:
        raise ValueError(
            f"Filtered sample count ({len(filtered)}) is smaller than cluster_num ({args.cluster_num}). "
            "Lower cluster_num or lower confidence_threshold."
        )

    encoder = load_sentence_encoder(args.load_sent_emb_model)
    pseudo_embeddings = encode_posts(encoder, filtered["post"])

    base_df = pd.read_csv(args.base_clustered_train, sep="\t")
    base_embeddings = encode_posts(encoder, base_df["post"])
    base_summary_df, base_prototype_df = build_base_cluster_reference(base_df, base_embeddings)

    kmeans = KMeans(n_clusters=args.cluster_num, random_state=args.seed, n_init="auto").fit(pseudo_embeddings)
    filtered["cluster"] = kmeans.labels_.tolist()

    cluster_summaries = []
    for cluster_id, cluster_df in filtered.groupby("cluster"):
        cluster_summaries.append(
            summarize_pseudo_cluster(
                cluster_df,
                cluster_id=cluster_id,
                min_cluster_size=args.min_cluster_size,
                purity_threshold=args.purity_threshold,
                balanced_margin=args.balanced_margin,
            )
        )

    summary_df = pd.DataFrame(cluster_summaries)
    summary_df = align_pseudo_clusters(
        summary_df=summary_df,
        kmeans_centers=np.array(kmeans.cluster_centers_),
        base_summary_df=base_summary_df,
        base_prototype_df=base_prototype_df,
        class_ratio_gap_threshold=args.class_ratio_gap_threshold,
    )

    filtered = filtered.merge(
        summary_df[
            [
                "cluster",
                "cluster_size",
                "count_0",
                "count_1",
                "positive_ratio",
                "majority_label",
                "majority_class_name",
                "majority_ratio",
                "is_balanced_cluster",
                "keep_cluster",
                "aligned_target_cluster",
                "aligned_centroid_sample",
                "aligned_similarity",
                "aligned_base_cluster_size",
                "aligned_base_positive_ratio",
                "aligned_base_majority_label",
                "aligned_base_class_name",
                "class_ratio_gap",
                "alignment_label_match",
                "keep_after_alignment",
            ]
        ],
        on="cluster",
        how="left",
    )

    selected = filtered.loc[filtered["keep_after_alignment"]].copy().reset_index(drop=True)

    ensure_output_dir_is_new(args.output_dir, label="pseudo cluster output directory")
    os.makedirs(args.output_dir, exist_ok=False)
    filtered_out = os.path.join(args.output_dir, "clustered_high_confidence_samples.csv")
    summary_out = os.path.join(args.output_dir, "cluster_summary.csv")
    selected_out = os.path.join(args.output_dir, "selected_cluster_samples.csv")
    meta_out = os.path.join(args.output_dir, "selection_metadata.json")

    filtered.to_csv(filtered_out, index=False)
    summary_df.to_csv(summary_out, index=False)
    selected.to_csv(selected_out, index=False)

    metadata = {
        "pseudo_predictions": args.pseudo_predictions,
        "base_clustered_train": args.base_clustered_train,
        "load_sent_emb_model": args.load_sent_emb_model,
        "confidence_threshold": args.confidence_threshold,
        "cluster_num": args.cluster_num,
        "min_cluster_size": args.min_cluster_size,
        "purity_threshold": args.purity_threshold,
        "balanced_margin": args.balanced_margin,
        "class_ratio_gap_threshold": args.class_ratio_gap_threshold,
        "seed": args.seed,
        "high_confidence_samples": len(filtered),
        "kept_clusters_before_alignment": int(summary_df["keep_cluster"].sum()),
        "kept_clusters_after_alignment": int(summary_df["keep_after_alignment"].sum()),
        "kept_samples": len(selected),
    }
    with open(meta_out, "w") as f:
        json.dump(metadata, f, indent=4)

    print(f"Saved {filtered_out}")
    print(f"Saved {summary_out}")
    print(f"Saved {selected_out}")
    print(f"High-confidence samples: {len(filtered)}")
    print(f"Kept clusters before alignment: {int(summary_df['keep_cluster'].sum())}")
    print(f"Kept clusters after alignment: {int(summary_df['keep_after_alignment'].sum())}")
    print(f"Kept samples: {len(selected)}")


if __name__ == "__main__":
    main()
